### ISSUE TITLE
Several errors under Awesome 4.3

### ISSUE THREAD

**Issue by jessequinn** [worron/awesome-config#26] opened 2019-05-04 11:12 UTC
Hi Worron,

I recently pulled your repo as stated in the README. However, when i start awesome i receive several errors.

```bash
dfparser.lua:63 attempt to index a nil value (local 'icon_file')
dfparser.lua:63 in upvalue 'is_format'
dfparser.lua:144 in function 'redflat.service.dfparser.lookup_icon'
dfparser.lua:217 ..in upvalue 'parse'
...
```
This is using:
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

and with the rc-colorless selected

I also have the ACYLS in the .icons and corrected that location in the theme.lua

any ideas?

**Comment by worron** [comment] 2019-05-04 13:07
Hi. Seems like some unexpected icon path in your desktop files. Can you please test this patch for `redflat` module
```diff
diff --git a/service/dfparser.lua b/service/dfparser.lua
index c1c8576..aac4897 100644
--- a/service/dfparser.lua
+++ b/service/dfparser.lua
@@ -131,6 +131,7 @@ function dfparser.lookup_icon(icon_file, style)
 			return icon_file
 		else
 			icon_file = string.match(icon_file, "([%a%d%-]+)%.")
+			if not icon_file then return df_icon end
 		end
 	end
 
```

**Comment by jessequinn** [comment] 2019-05-04 13:25
Works, but I feel like i am missing some icons for windows or is that normal? For instance, there are three small bars adjacent to a blue highlight bar when using rc-colorless above google chrome or a terminal.

**Comment by worron** [comment] 2019-05-04 14:03
It's by design. [Here's](https://github.com/worron/awesome-config/issues/4#issuecomment-295304210) more info.

Also If you are heavily interested in classic titlebar with full size icons, you can check `devel` branch. I've prepared new titlebar style for future big update, but work still in progress and `devel` branch  is may be unstable.

**Comment by jessequinn** [comment] 2019-05-05 19:23
Thanks will look into it. 

On a side note, I installed Manjaro-Awesome community edition and it had the same issue, but your patch works.

In addition, I have been playing around with your lua code and have fun some possible bugs?

May be I will compile a list and send to your somehow.

For instance, I noticed that, at least for me, the temperature from `hddtemp` doesn't work get passed correctly as grep treats the input as binary so I needed to add `-a` found in the system.lua

```
"echo | curl --connect-timeout 1 -fsm 3 telnet://127.0.0.1:" .. port .. " | grep -a " .. disk
```

or a issue with transmission, it assumes a RPC connection is available, but you do not list the host and possible port assuming none default, but either way localhost is required in the desktop-config.lua

```bash
async      = "transmission-remote localhost -l"
```

**Comment by worron** [comment] 2019-05-06 16:04
>to work with more than one hdd temperature I had to rewrite a portion of the function.

Thanks, it's useful. I've add all fixes to `devel` branch, will be merged into `master` with next update.
>but either way, localhost is required in the desktop-config.lua

All '*-config.lua' files meant to be personal user setup heavy depended on environment.  Just edit it for your needs without hesitate. But please report any fixes needed under `redflat` module (like hdd temperature issue above).
>I get we are suppose to figure this out, but may I suggest, that whoever is interested put together a wiki on this to save time when it comes to customizing.

If I get it right you are talking about creating proper documentation for this config. It's really right and good idea but not for nearest future I'm afraid. There are a lot things to fix at terms of code first of all and I'm limited in time to spend on it since it's hobby project.

**Closed** 2019-05-12 18:52 UTC
